name: SqlCash
main: delos\SqlCash\SqlCash
author: delos
api:
- 1.13.0
- 2.0.0
version: 1.0.4-Organic

commands:
 지불:
  permission: sqlcash.command.pay
  description: 캐쉬 지불 커맨드 
 캐쉬:
  permission: sqlcash.command.cash
  description: 오피 전용 캐쉬 관리 커맨드
 내캐쉬:
  permission: sqlcash.command.mycash
  description: 자신의 캐쉬 확인
  
permissions:
 sqlcash.command.cash:
  default: OP
 sqlcash.command.mycash:
  default: true
 sqlcash.command.pay:
  default: true